# fly.toml app configuration file generated for agriflight-api on 2025-12-21T02:14:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agriflight-api'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  AGENT_ID = 'ag_019a20d4b1737572b6fe4eb8e100f91d'
  CF_AIG_GATEWAY_URL = 'https://gateway.ai.cloudflare.com/v1/2a14c12991da690bcfb33f07fead3834/agx1'
  CF_AIG_TOKEN = '2a14c12991da690bcfb33f07fead3834'

  MONGODB_URI = 'mongodb://atlas-sql-68fa4b2835318b5177d9f22e-jahs9r.a.query.mongodb.net/silvercloud?ssl=true&authSource=admin'
  NEXT_PUBLIC_AI_PROVIDER = 'xai'
  NODE_ENV = 'production'

  PORT = '3001'
  DATABASE_URL = '/data/agriflight.db'

[mounts]
  source = 'agriflight_data'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512

